### ISSUE TITLE
Provide an option to import ALL GA

### ISSUE THREAD

**Issue by daKrueml** [iobroker-community-adapters/ioBroker.openknx#331]
**Is your feature request related to a problem? Please describe.**
When importing the GA from an XML all unassigned GA will not be imported:
"The GA is not connected to a KO in ETS"

**Describe the solution you'd like**
Provide an option to override this behaviour. Reason: When using the Gira X1 there might be a possibility that there are configured GAs that are configured in ETS but not actively connected to an object. If you want to utilize the KNX Bus to transfer objects between the X1 and iobroker without using any physical KNX device you have to have those blank GAs.

**Comment by boellner** [comment]
Could you please past the relevant xml part which is causing the conflict?

Message text is also: Not adding .. because no DPT is assigned to ..
"DPTs" is not existent in the xml export. This makes it impossible to determine the correct datatype.

**Comment by ChriD** [comment]
> Could you please explain why this is the case to understand your use case better. At the moment I do not understand why any device is sending on this address.

I am not sure what @daKrueml's usecase is, but my usecase a few years ago was, that i had DIY KNX devices which where not defined in the ETS and for those i would need to created unassigned GA's to get those GA's in the adapter. Manually adding GA's wont work right? There is a workaround for that if we are using dummy device applications in ETS (there are some from gira i think)

**Comment by daKrueml** [comment]
The use case is simply communicating from the Gira X1/G1 Universe to
iobroker via KNX. A simple UI to either add GAs manually or adding a data
type (whoch seems to be the underlying error) for a GA would be totally
sufficient. I just want iobroker to be able to listen to a specified GA
even if it is not mapped in ETS.

**Comment by TA2k** [comment]
There was a PR with the option to add all GA but was declined by the owner because he see no need for this
https://github.com/iobroker-community-adapters/ioBroker.openknx/pull/80

**Comment by boellner** [comment]
If its not part of the ETS configuration than the XML import wont see it.  For this you have the dummy devices. ETS should be the master of all configurations. Anything else will lead to a incomplete ETS configuration.

@daKrueml
You need the ETS to configure your bus as far as I understand and then you import it with GPA into your Gira X1/G1. 
I did not understand why you need to add additional data for the adapter around the regular import mechanism.

**Comment by daKrueml** [comment]
The GAs I am trying to import are Part of the ETC and configured. They are
just empty.

If you use the Gira X1 you mimic the ETS GAs and use them in as Gira calls
them Datapoints. These Datapoints can be used in Logic and are able to
communicate on the corresponding GAs. But they are not visible in ETS. If I
maybe want to log those GAs to an influx DB via ioBroker I can't even tell
openknx to listen to them. That is why. And using a dummy device is a
pretty dirty way over this. Actually there is no reason NOT to import empty
GAs - at least as an option.

**Comment by felsnerino** [comment]
Hi, it actually is the right way to use a dummy for that. For example I have all addresses that I want to "observe/log with influx" also mapped to my dummy device: (IObroker and EibPort). Also all visualization GAs have to be mapped (in my case EIBPort). 
![image](https://user-images.githubusercontent.com/101385408/216959651-d7c554c3-a8bf-4cb1-acf2-55041d83f7e4.png)

- By having them in the ETS, you know, if an address is already in use regardless where. 
- You also can define a DataType which is then again correctly used in OpenKNX ("An/Aus" vs. "0/1"). 
- Also filtering in Routers/LKs works then properly 
- Bus Monitor works properly, etc. 
 
I have my OpenKNX actually on the IP Backbone of my routers, due to traffic... Also there is the logic. It is actually not too much effort, if you create "clever dynamic views", Devices and GAs... then you can easily drag and drop them and assign mass adresses, there are also paid plugins for that... 

Check also this thread: [Linkt to KNXForum](https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1578402-dummy-schnell-den-gas-zuordnen)

Otherwise, I don't want to judge on the usefulness of importing empty addresses if they "seem to be NOT used"...

**Comment by boellner** [comment]
use a dummy for that
