### ISSUE TITLE
changes to answer_groupValueResponse and autoread gone after new import

### ISSUE THREAD

**Issue by tillsteinbach** [iobroker-community-adapters/ioBroker.openknx#366]
**Describe the bug**  
When I do changes to the answer_groupValueResponse or autoread flags those changes are gone after a new import

**To Reproduce**  
1. import group addresses through XML file
2. make changes to answer_groupValueResponse or autoread
3. import same XML file again
4. check answer_groupValueResponse or autoread

**Expected behavior**  
Changes to the flags should not be reset after import.

**Versions:**  
 - Adapter version: v0.5.2
 - JS-Controller version: 4.0.24
 - Node version: v16.15.1
 - Operating system: official Docker image

**Additional context**  
This might be relevant for further parameters in native section

**Comment by Percy2Live** [comment]
I can confirm that. This is a dealbreaker if you're using logic moduls in KNX - most of them only work if all input states have a known value. I was wondering why my KNX logics didn't work anymore until I noticed that the KNX device which is responsible for the logic desperately tries to read the GA's which come from ioBroker.

For anybody who has the same issue: here's a small script as workaround until this bug is fixed. Simply enter all datapoints which need to react to a GroupValueRead in the array at the top and run it after you updated the XML in ioBroker:

```
var listOfObjects = [
'openknx.0.Alarme_und_Alarmanlage.Fenster-_und_Türkontakte.EG-Garagentür-Geöffnet'/*EG-Garagentür-Geöffnet*/,
'openknx.0.Alarme_und_Alarmanlage.Fenster-_und_Türkontakte.OG-Ankleide-Fenster-Geöffnet'/*OG-Ankleide-Fenster-Geöffnet*/,
//Enter further datapoints here
]

for(let index = 0, len = listOfObjects.length; index < len; ++index)
{
    //Enable GroupValueRead answer
    extendObject(listOfObjects[index], {native: {answer_groupValueResponse: false}});
	//As the adapter only responds if the value of a datapoint is not null, replace null values, e.g. with false
    if(getState(listOfObjects[index]).val == null) setState(listOfObjects[index], false);
}
//Restart adapter to apply changes
//Stop it first...
    setState("system.adapter.openknx.0.alive", false);
//Enable it again with a short delay
    setTimeout(function() {
        setState("system.adapter.openknx.0.alive", true);
        //Stop this script
        stopScript();
    }, 5000);

```

**Comment by boellner** [comment]
What about checking these two options:
![image](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/86853627/4342c3ec-1e8c-4211-9e03-c434aacb681a)
-it will not create newly any objects that existed and I assume manual settings persist
-non existing GAs are cleaned up
