### ISSUE TITLE
Please provide a german translation of the readme

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#97]
95% of the ioBroker user a german please provide a translation

**Comment by boellner** [comment]
and 63% of Germans understand English;
if someone wants to contribute please feel free, else its a resource conflict/quality conflict to maintain translation

**Comment by TA2k** [comment]
Adapter content is also translated why not the readme.
Contributed translation was deleted why contribute again?

**Comment by boellner** [comment]
I prefer not to have a translation over having a not updated translation, and who needs can easily help himself out

**Comment by TA2k** [comment]
Why the adapter is then translated. Will you remove the translation?
Maybe the community want to maintain the translation. Because your are not willing to this is no reason to close the request

**Comment by boellner** [comment]
Adapter is translated because it is built in the toolchain. Usefulness is a different question.
I close this request again soon unless you present me that person that is willing to maintain continuously the trainslation or do it by yourself.

**Comment by TA2k** [comment]
It think it is not the idea behind feature request to close them if they are not solved immediately.
It is also hard to find person when their work is removed by the owner of the adapter without discussion because owner of the adapter don't like the idea

**Comment by Videonisse** [comment]
I agree, instead maybe tags can be used to give feedback on what's needed to proceed to the next step? The "Ping Pong" game closing and reopening Isses must be just frustrating and less constructive.

**Comment by boellner** [comment]
@TA2k then please keep your work up to date. You refuse to participate in the project and start to bug about everyting. This is wasting my time and this is not the way to continue.
There is only little to no benefit in a translation in the manual. And I dont see other projects spending this useless effort. 
This issue is now closed and should be opened only if someone comes up with a produtive proposal. Requesting useless work from others is not helpful!

**Comment by TA2k** [comment]
Please let the issue open that somebody can see it and assign it to himself.
Closes issues are not visible to others
It looks like your are not familiar with working in community or other persons.

**Comment by boellner** [comment]
Nobody is going to work on this unneccesary translation and the project does not have the need for this. Check the other repos to get an understanding what is common and what not. I close this again because this request will stay open forever and I dont want a messed up board. Im advising you for the last time to stop sabotaging the project and wasting my time with useless things
